language: node_js
node_js:
- node
- 8
- 6
os:
- linux
- osx
osx_image: xcode7.3
script: yarn run travis
after_success:
- cat coverage/lcov.info | node_modules/.bin/coveralls --verbose
cache:
  yarn: true
jobs:
  include:
  - stage: release
    node_js: 8
    os: linux
    after_success: yarn travis-deploy-once "yarn semantic-release"
env:
  global:
  - BUILD_LEADER_ID=7
  - secure: nddAlCZK+QQzX1OK+MaDgn8Ub05GHP1H5BcBiQvuHqSok3iUaVoPgTt6jdDHju8pDMlZ97Op9HlwEAfBhOOFxAQPirfsdAK6QT5r0yMlB6eLnpRPPsMCa2k+q2oA5uXx6/QtC20jBlsuvuXWbV/M73cELP3qOA8vEU+FR5DWwMfYWqM2+9wY7N5hsH8GgpdVXU+/Vfo5b+zD2S+IlIvGVgLhxl+w8VBJr7RGa5kRNmER6zVdikxjigME9Y5cdLFS9JeAO84Ukurml2wTrtDvuoSgaw0L3JtquT/ebPdChRE7j8ANQ8K21VmoMOm9t5TK1jlvenvk9Op3xecaawSmZtedCfdmdWxxn7gbUTvgpu7ddgHtL088Lfn7yHfLz+q7EAfP/U7fcxbvMJwILsU6ojyFkwoZYj6r33ue1S4pjM9zQWJllgC5+eDmJHmF8tYTjdz0R37gzNmqmrUOrro9lWIpaQZgboCBnpzi9c8C6bT98PEG+g011c2dlJ4y1n9cmSoiW7MqfOTUaTUTwaxSrM1oYSJN5cknzntjTrwjPNSowngjV++aiwAoJydOWATZfRjs3WKQnZaAS220+H/vemWEZ6lIUikSIcsh7HRGsFRUubGCiFOchneLLIMhHcTzgj3wuVFhZCimgD2KzrNxX5rdLXuQ5dRiZsoridlQSIg=
  - secure: qZPdC+IY8nsGMOIQwwW3COStQsFGzkm/9UQATAzhBeKWlbM5F0oBWSSmcHIsczATlNcJPwiY/Fzd1BqTbJ0tKl1JYnNfUMTp3MCvLlmU1OkYV+RfKK+dgXU5z9zRjhpOaSR8AeqkbSvcAseIEaAt7HEymkw1Hde+C6qtPL/FIq05+OZ4v+Zz+aT3lzVulMKvR3x2SjNVI58CCUfDGpHU0ZHCEW+VhfJ/WJZluLOhoeLJaj5G5z/8+yzqJSwD3piXOBZ6OjPwmvQueXar4XqvcIRAFJyDhIXerhuHLp1rKitBDtcCbuFtVvVbnsp3U+t2D2ygrYj1K1JXEQvf9NeMgDdPQLLSUC9sH/alpwNkmNxh5tWpoLbX0OnCtiVecL7GMhXssCcNqGied0IBzXDazXiVyzDOTXl9L0D9MAh0hmynb4tXr9ZXH3092RfJOieU0k8hdNFdCM+/hMPiVl9ezBEHW0eG3Wm5en1ouVu09RNXxS0HqaDjfnrgIBc3J3ltbTeQeWH2QqacV72DcHHNKjf1aTvvNKmi7jJCK5Hq+DmkmvDTh2TVLThykr8/0FWhO9ecS7rPT3ZZLMcJVQ9IBUxH639Ho1ekjZLnoG1G5U4K3tg/Qj6+YZ+MkYqFlpvqnmg/09CB9VDbiuuPobS3ae3Brq0zp+7LxbXVS0XJ3Bg=
