language: node_js
node_js:
  - node
  - 6
os:
  - linux
  - osx
osx_image: xcode7.3
script: yarn run travis
after_success:
  - cat coverage/lcov.info | node_modules/.bin/coveralls --verbose
cache:
  yarn: true
